[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo build --filter=@yantrix/web --concurrency=1"]

[start]
cmd = "pnpm --filter @yantrix/web start"
