packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "esbuild"
  - "prisma"
  - "unrs-resolver"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  prisma: true
  unrs-resolver: true
